export const FETCHING_COUNTRY_START = "FETCHING_COUNTRY_START";
export const FETCHING_COUNTRY_SUCCESS = "FETCHING_COUNTRY_SUCCESS";
export const FETCHING_COUNTRY_FAILURE = "FETCHING_COUNTRY_FAILURE";
export const FETCHING_TOP_COUNTRIES = 'FETCHING_TOP_COUNTRIES';
export const FETCHING_TOP_COUNTRIES_SUCCESS = 'FETCHING_TOP_COUNTRIES_SUCCESS';
export const FETCHING_TOP_COUNTRIES_FAILURE = 'FETCHING_TOP_COUNTRIES_FAILURE';
export const FETCHING_US_START = "FETCHING_US_START";
export const FETCHING_US_SUCCESS = 'FETCHING_US_SUCCESS';
export const FETCHING_US_FAILURE = 'FETCHING_US_FAILURE';
export const IS_UPDATING_START = 'IS_UPDATING_START';
export const IS_UPDATING_SUCCESS = 'IS_UPDATING_SUCCESS';
export const IS_UPDATING_FAILURE = 'IS_UPDATING_FAILURE'

