export const FETCHING_COUNTRY_START = "FETCHING_COUNTRY_START";
export const FETCHING_COUNTRY_SUCCESS = "FETCHING_COUNTRY_SUCCESS";
//export const FETCHING_COUNTRY_FAILURE = "FETCHING_COUNTRY_FAILURE";
export const FETCHING_TOP_COUNTRIES = 'FETCHING_TOP_COUNTRIES';
export const FETCHING_TOP_COUNTRIES_SUCCESS = 'FETCHING_TOP_COUNTRIES_SUCCESS';
export const FETCHING_TOP_COUNTRIES_FAILURE = 'FETCHING_TOP_COUNTRIES_FAILURE';