export const countrylist = [
  {
    country: 'China',
    id: 2,
    cases: true,
    deaths: true,
    few_regions: false,
    regions: true,
    not_cumu: true,
  },
  {
    country: 'Italy',
    id: 25,
    cases: true,
    deaths: true,
    few_regions: false,
    regions: true,
    not_cumu: true,
  },
  {
    country: 'USA',
    id: 8,
    cases: true,
    deaths: true,
    regions: true,
    few_regions: false,
    not_cumu: false,
  },
  {
    country: 'Iran',
    id: 32,
    cases: true,
    deaths: true,
    few_regions: false,
    regions: true,
    not_cumu: true,
  },
  {
    country: 'France',
    id: 14,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: true,
  },
  {
    country: 'Korea, Republic of',
    id: 6,
    cases: true,
    deaths: false,
    regions: true,
    not_cumu: true,
  },
  {
    country: 'Spain',
    id: 29,
    cases: true,
    deaths: false,
    regions: true,
    not_cumu: true,
  },
  {
    country: 'Germany',
    id: 19,
    cases: true,
    deaths: false,
    regions: true,
    not_cumu: true,
  },
  {
    country: 'Switzerland',
    id: 42,
    cases: true,
    deaths: false,
    regions: true,
    not_cumu: true,
  },
  {
    country: 'Iraq',
    id: 38,
    cases: true,
    deaths: true,
    regions: true,
    not_cumu: true,
  },
  {
    country: 'United Kingdom',
    id: 26,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: true,
  },
  {
    country: 'Netherlands',
    id: 53,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: true,
  },
  {
    country: 'Canada',
    id: 17,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: true,
  },
  {
    country: 'Australia',
    id: 15,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: true,
  },
  {
    country: 'Denmark',
    id: 51,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: true,
  },

  //countries with no regions
  {
    country: 'Austria',
    id: 40,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Belgium',
    id: 30,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Norway',
    id: 49,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Sweden',
    id: 28,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Portugal',
    id: 72,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Malaysia',
    id: 16,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Brazil',
    id: 44,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Czechia',
    id: 67,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Japan',
    id: 4,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Ireland',
    id: 66,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Diamond Princess',
    id: 5,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Qatar',
    id: 63,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Greece',
    id: 45,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Slovenia',
    id: 85,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Israel',
    id: 33,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Singapore',
    id: 11,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Finland',
    id: 21,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Bahrain',
    id: 37,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Estonia',
    id: 52,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Pakistan',
    id: 46,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Iceland',
    id: 61,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Hong Kong',
    id: 10,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Poland',
    id: 83,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Thailand',
    id: 3,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Philippines',
    id: 23,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Romania',
    id: 50,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Egypt',
    id: 31,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Saudi Arabia',
    id: 77,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Indonesia',
    id: 70,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Chile',
    id: 82,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Kuwait',
    id: 35,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Uruguay',
    id: 129,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Lebanon',
    id: 34,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'India',
    id: 22,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'San Marino',
    id: 54,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'United Arab Emirates',
    id: 20,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Luxembourg',
    id: 65,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Peru',
    id: 96,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Taiwan',
    id: 7,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Russia',
    id: 27,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Vietnam',
    id: 12,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'South Africa',
    id: 88,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Slovakia',
    id: 93,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Kazakhstan ',
    id: 126,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Panama',
    id: 108,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Mexico',
    id: 60,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Bulgaria',
    id: 103,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Brunei',
    id: 106,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Algeria',
    id: 43,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Croatia',
    id: 41,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Serbia',
    id: 92,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Argentina',
    id: 80,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Venezuela',
    id: 128,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Albania',
    id: 104,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Cyprus',
    id: 105,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Palestine, State of',
    id: 87,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Ecuador',
    id: 64,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Costa Rica',
    id: 101,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Colombia',
    id: 95,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Hungary',
    id: 84,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Georgia',
    id: 48,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Latvia',
    id: 76,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Morocco',
    id: 78,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Belarus',
    id: 58,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Armenia',
    id: 69,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Senegal',
    id: 75,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Azerbaijan',
    id: 59,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Uzbekistan',
    id: 141,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Malta',
    id: 98,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Bosnia and Herzegovina',
    id: 86,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Oman',
    id: 39,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Kosovo',
    id: 131,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'North Macedonia',
    id: 47,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Tunisia',
    id: 74,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Sri Lanka',
    id: 18,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Afghanistan',
    id: 36,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Maldives',
    id: 97,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Lithuania',
    id: 56,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Moldova',
    id: 100,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Bolivia',
    id: 113,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Macau',
    id: 9,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Dominican Republic',
    id: 68,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Rwanda',
    id: 137,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Jamaica',
    id: 111,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Montenegro',
    id: 154,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'New Zealand',
    id: 57,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Cambodia',
    id: 24,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Paraguay',
    id: 99,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Liechtenstein',
    id: 81,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Jordan',
    id: 73,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Turkey',
    id: 112,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Ghana',
    id: 122,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Ethiopia',
    id: 125,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Guatemala',
    id: 132,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Puerto Rico',
    id: 147,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Tanzania',
    id: 150,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Aruba',
    id: 134,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'French Guiana',
    id: 138,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Bangladesh',
    id: 102,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Kenya',
    id: 123,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Equatorial Guinea',
    id: 146,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Seychelles',
    id: 142,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Cuba',
    id: 118,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Mauritius',
    id: 161,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Bahamas',
    id: 148,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Cura\\u00e7ao',
    id: 136,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Kyrgyzstan',
    id: 156,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Ukraine',
    id: 79,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Zimbabwe',
    id: 169,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Honduras',
    id: 114,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Congo (the Democratic Republic of the)',
    id: 109,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Burkina Faso',
    id: 110,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Monaco',
    id: 62,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Liberia',
    id: 152,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Haiti',
    id: 165,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Trinidad and Tobago',
    id: 120,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Cameroon',
    id: 90,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Mauritania',
    id: 133,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: "C\u00c3\u00b4te d'Ivoire",
    id: 115,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Benin',
    id: 151,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Nigeria',
    id: 55,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Zambia',
    id: 158,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Barbados',
    id: 155,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Namibia',
    id: 139,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Niger',
    id: 164,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Cape Verde',
    id: 166,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Angola',
    id: 167,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Madagascar',
    id: 168,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Papua New Guinea',
    id: 170,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Nepal',
    id: 13,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Guyana',
    id: 117,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'French Polynesia',
    id: 116,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Sudan',
    id: 124,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Timor Leste',
    id: 171,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Mongolia',
    id: 107,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Togo',
    id: 94,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Bhutan',
    id: 91,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Guinea',
    id: 127,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Vatican City',
    id: 89,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Suriname',
    id: 130,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Gabon',
    id: 121,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Mozambique',
    id: 172,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Antigua and Barbuda',
    id: 135,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Saint Vincent and the Grenadines',
    id: 119,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Eswatini',
    id: 140,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Andorra',
    id: 71,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Central African Republic',
    id: 143,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Congo',
    id: 144,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Cayman Islands',
    id: 145,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Grenada',
    id: 173,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Somalia',
    id: 149,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Greenland',
    id: 153,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Djibouti',
    id: 157,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'El Salvador',
    id: 159,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Nicaragua',
    id: 160,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Fiji',
    id: 162,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
  {
    country: 'Chad',
    id: 163,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: false,
  },
];
