export const countrylist = [
  {
    country: 'China',
    id: 2,
    cases: true,
    deaths: true,
    few_regions: false,
    regions: true,
    not_cumu: true,
  },
  {
    country: 'Italy',
    id: 25,
    cases: true,
    deaths: true,
    few_regions: false,
    regions: true,
    not_cumu: true,
  },
  {
    country: 'USA',
    id: 8,
    cases: true,
    deaths: true,
    regions: true,
    few_regions: false,
    not_cumu: false,
  },
  {
    country: 'Iran',
    id: 32
  },
  {
    country: 'France',
    id: 14,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: true,
  },
  {
    country: 'Korea, Republic of',
    id: 6,
    cases: true,
    deaths: false,
    regions: true,
    not_cumu: true,
  },
  {
    country: 'Spain',
    id: 29,
    cases: true,
    deaths: false,
    regions: true,
    not_cumu: true,
  },
  {
    country: 'Germany',
    id: 19,
    cases: true,
    deaths: false,
    regions: true,
    not_cumu: true,
  },
  {
    country: 'Switzerland',
    id: 42,
    cases: true,
    deaths: false,
    regions: true,
    not_cumu: true,
  },
  {
    country: 'Iraq',
    id: 38,
    cases: true,
    deaths: true,
    regions: true,
    not_cumu: true,
  },
  {
    country: 'United Kingdom',
    id: 26,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: true,
  },
  {
    country: 'Netherlands',
    id: 53,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: true,
  },
  {
    country: 'Canada',
    id: 17,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: true,
  },
  {
    country: 'Australia',
    id: 15,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: true,
  },
  {
    country: 'Denmark',
    id: 51,
    cases: true,
    deaths: true,
    recoveries: true,
    regions: true,
  },

  //countries with no regions
  { country: 'Afghanistan', id: 36 },
  { country: 'Albania', id: 104 },
  { country: 'Algeria', id: 43 },
  { country: 'Andorra', id: 71 },
  { country: 'Angola', id: 167 },
  { country: 'Antigua and Barbuda', id: 135 },
  { country: 'Argentina', id: 80 },
  { country: 'Armenia', id: 69 },
  { country: 'Aruba', id: 134 },
  { country: 'Austria', id: 40 },
  { country: 'Azerbaijan', id: 59 },
  { country: 'Bahamas', id: 148 },
  { country: 'Bahrain', id: 37 },
  { country: 'Bangladesh', id: 102 },
  { country: 'Barbados', id: 155 },
  { country: 'Belarus', id: 58 },
  { country: 'Belgium', id: 30 },
  { country: 'Benin', id: 151 },
  { country: 'Bhutan', id: 91 },
  { country: 'Bolivia', id: 113 },
  { country: 'Bosnia and Herzegovina', id: 86 },
  { country: 'Brazil', id: 44 },
  { country: 'Brunei', id: 106 },
  { country: 'Bulgaria', id: 103 },
  { country: 'Burkina Faso', id: 110 },
  { country: 'Cambodia', id: 24 },
  { country: 'Cameroon', id: 90 },
  { country: 'Cape Verde', id: 166 },
  { country: 'Cayman Islands', id: 145 },
  { country: 'Central African Republic', id: 143 },
  { country: 'Chad', id: 163 },
  { country: 'Chile', id: 82 },
  { country: 'Colombia', id: 95 },
  { country: 'Congo', id: 144 },
  { country: 'Congo (the Democratic Republic of the)', id: 109 },
  { country: 'Costa Rica', id: 101 },
  { country: 'Croatia', id: 41 },
  { country: 'Cuba', id: 118 },
  { country: 'Cura\\u00e7ao', id: 136 },
  { country: 'Cyprus', id: 105 },
  { country: 'Czechia', id: 67 },
  { country: "CÃ´te d'Ivoire", id: 115 },
  { country: 'Diamond Princess', id: 5 },
  { country: 'Djibouti', id: 157 },
  { country: 'Dominican Republic', id: 68 },
  { country: 'Ecuador', id: 64 },
  { country: 'Egypt', id: 31 },
  { country: 'El Salvador', id: 159 },
  { country: 'Equatorial Guinea', id: 146 },
  { country: 'Estonia', id: 52 },
  { country: 'Eswatini', id: 140 },
  { country: 'Ethiopia', id: 125 },
  { country: 'Fiji', id: 162 },
  { country: 'Finland', id: 21 },
  { country: 'French Guiana', id: 138 },
  { country: 'French Polynesia', id: 116 },
  { country: 'Gabon', id: 121 },
  { country: 'Georgia', id: 48 },
  { country: 'Ghana', id: 122 },
  { country: 'Greece', id: 45 },
  { country: 'Greenland', id: 153 },
  { country: 'Grenada', id: 173 },
  { country: 'Guatemala', id: 132 },
  { country: 'Guinea', id: 127 },
  { country: 'Guyana', id: 117 },
  { country: 'Haiti', id: 165 },
  { country: 'Honduras', id: 114 },
  { country: 'Hong Kong', id: 10 },
  { country: 'Hungary', id: 84 },
  { country: 'Iceland', id: 61 },
  { country: 'India', id: 22 },
  { country: 'Indonesia', id: 70 },
  { country: 'Ireland', id: 66 },
  { country: 'Israel', id: 33 },
  { country: 'Jamaica', id: 111 },
  { country: 'Japan', id: 4 },
  { country: 'Jordan', id: 73 },
  { country: 'Kazakhstan ', id: 126 },
  { country: 'Kenya', id: 123 },
  { country: 'Kosovo', id: 131 },
  { country: 'Kuwait', id: 35 },
  { country: 'Kyrgyzstan', id: 156 },
  { country: 'Latvia', id: 76 },
  { country: 'Lebanon', id: 34 },
  { country: 'Liberia', id: 152 },
  { country: 'Liechtenstein', id: 81 },
  { country: 'Lithuania', id: 56 },
  { country: 'Luxembourg', id: 65 },
  { country: 'Macau', id: 9 },
  { country: 'Madagascar', id: 168 },
  { country: 'Malaysia', id: 16 },
  { country: 'Maldives', id: 97 },
  { country: 'Malta', id: 98 },
  { country: 'Mauritania', id: 133 },
  { country: 'Mauritius', id: 161 },
  { country: 'Mexico', id: 60 },
  { country: 'Moldova', id: 100 },
  { country: 'Monaco', id: 62 },
  { country: 'Mongolia', id: 107 },
  { country: 'Montenegro', id: 154 },
  { country: 'Morocco', id: 78 },
  { country: 'Mozambique', id: 172 },
  { country: 'Namibia', id: 139 },
  { country: 'Nepal', id: 13 },
  { country: 'New Zealand', id: 57 },
  { country: 'Nicaragua', id: 160 },
  { country: 'Niger', id: 164 },
  { country: 'Nigeria', id: 55 },
  { country: 'North Macedonia', id: 47 },
  { country: 'Norway', id: 49 },
  { country: 'Oman', id: 39 },
  { country: 'Pakistan', id: 46 },
  { country: 'Palestine, State of', id: 87 },
  { country: 'Panama', id: 108 },
  { country: 'Papua New Guinea', id: 170 },
  { country: 'Paraguay', id: 99 },
  { country: 'Peru', id: 96 },
  { country: 'Philippines', id: 23 },
  { country: 'Poland', id: 83 },
  { country: 'Portugal', id: 72 },
  { country: 'Puerto Rico', id: 147 },
  { country: 'Qatar', id: 63 },
  { country: 'Romania', id: 50 },
  { country: 'Russia', id: 27 },
  { country: 'Rwanda', id: 137 },
  { country: 'Saint Vincent and the Grenadines', id: 119 },
  { country: 'San Marino', id: 54 },
  { country: 'Saudi Arabia', id: 77 },
  { country: 'Senegal', id: 75 },
  { country: 'Serbia', id: 92 },
  { country: 'Seychelles', id: 142 },
  { country: 'Singapore', id: 11 },
  { country: 'Slovakia', id: 93 },
  { country: 'Slovenia', id: 85 },
  { country: 'Somalia', id: 149 },
  { country: 'South Africa', id: 88 },
  { country: 'Sri Lanka', id: 18 },
  { country: 'Sudan', id: 124 },
  { country: 'Suriname', id: 130 },
  { country: 'Sweden', id: 28 },
  { country: 'Taiwan', id: 7 },
  { country: 'Tanzania', id: 150 },
  { country: 'Thailand', id: 3 },
  { country: 'Timor Leste', id: 171 },
  { country: 'Togo', id: 94 },
  { country: 'Trinidad and Tobago', id: 120 },
  { country: 'Tunisia', id: 74 },
  { country: 'Turkey', id: 112 },
  { country: 'Ukraine', id: 79 },
  { country: 'United Arab Emirates', id: 20 },
  { country: 'Uruguay', id: 129 },
  { country: 'Uzbekistan', id: 141 },
  { country: 'Vatican City', id: 89 },
  { country: 'Venezuela', id: 128 },
  { country: 'Vietnam', id: 12 },
  { country: 'Zambia', id: 158 },
  { country: 'Zimbabwe', id: 169 },
];
