export const Regions = {
  USA: [
    'NEW ENGLAND',
    'Mid-Atlantic',
    'East North Central',
    'West North Central',
    'South Atlantic',
    'East South Central',
    'West South Central',
    'Mountain',
    'Pacific',
    'Puerto Rico',
    'Apple',
  ],
  China: [
    'Hubei',
    'Guangdong',
    'Beijing',
    'Shanghai',
    'Zhejiang',
    'Tianjin',
    'Chongqing',
    'Jiangxi',
    'Shandong',
    'Henan',
    'Hunan',
    'Sichuan',
    'Yunnan',
    'Fujian',
    'Liaoning',
    'Hainan',
    'Anhui',
    'Guizhou',
    'Guangxi',
    'Hebei',
    'Jilin',
    'Heilongjiang',
    'Shanxi',
    'Xinjiang',
    'Gansu',
    'Inner Mongolia',
  ],
  Italy: [
    'Lombardia',
    'Veneto',
    'Emilia - Romagna',
    'Piemonte',
    'Trentino',
    'Sicilia',
    'Toscana',
    'Liguria',
    'Marche',
    'Puglia',
    'Lazio',
    'Abruzzo',
    'Calabria',
    'Campania',
    'Umbria',
    'Friuli',
    'Bolzano',
    'Sardegna',
    'Basilicata',
    "Valle d'Aosta",
  ],
};
