export const Regions = {
  USA: [
    'New York       ',
    'Washington',
    'California',
    'New Jersey',
    'Michigan',
    'Illinois',
    'Florida',
    'Louisiana',
    'Texas',
    'Massachusetts',
    'Georgia',
    'Pennsylvania',
    'Colorado',
    'Tennessee',
    'Wisconsin',
    'North Carolina',
    'Ohio',
    'Connecticut',
    'Maryland',
    'South Carolina',
    'Nevada',
    'Virginia',
    'Mississippi',
    'Minnesota',
    'Utah',
    'Alabama',
    'Indiana',
    'Arkansas',
    'Arizona',
    'Oregon',
    'Kentucky',
    'District of Columbia',
    'Missouri',
    'Maine',
    'Iowa',
    'Rhode Island',
    'Kansas',
    'New Hampshire',
    'Oklahoma',
    'Diamond Princess',
    'Delaware',
    'New Mexico',
    'Nebraska',
    'Hawaii',
    'Idaho',
    'Vermont',
    'North Dakota',
    'Grand Princess',
    'Wyoming',
    'Montana',
    'Puerto Rico',
    'Alaska',
    'Guam',
    'South Dakota',
    'West Virginia',
    'United States Virgin Islands    ',
  ],
  China: [
    'Hubei',
    'Guangdong',
    'Beijing',
    'Shanghai',
    'Zhejiang',
    'Tianjin',
    'Chongqing',
    'Jiangxi',
    'Shandong',
    'Henan',
    'Hunan',
    'Sichuan',
    'Yunnan',
    'Fujian',
    'Liaoning',
    'Hainan',
    'Anhui',
    'Guizhou',
    'Guangxi',
    'Hebei',
    'Jilin',
    'Heilongjiang',
    'Shanxi',
    'Xinjiang',
    'Gansu',
    'Inner Mongolia',
  ],
  Italy: [
    'Lombardia',
    'Veneto',
    'Emilia - Romagna',
    'Piemonte',
    'Trentino',
    'Sicilia',
    'Toscana',
    'Liguria',
    'Marche',
    'Puglia',
    'Lazio',
    'Abruzzo',
    'Calabria',
    'Campania',
    'Umbria',
    'Friuli',
    'Bolzano',
    'Sardegna',
    'Basilicata',
    "Valle d'Aosta",
  ],
  Iran: [
    'Qom',
    'Markazi',
    'Tehran',
    'Gilan',
    'Mazandaran',
    'Hamadan',
    'Isfahan',
    'Fars',
    'Khorasan Razavi',
    'Alborz',
    'Hormozgan',
    'Khuzestan',
    'Sistan and Baluchestan',
    'Kohgiluyeh and Boyer-Ahmad',
    'Kermanshah',
    'Ardabil',
    'Lorestan',
    'Semnan',
    'Kurdistan',
    'Yazd',
    'East Azerbaijan',
    'West Azerbaijan',
    'Qazvin',
    'Golestan',
    'Ilam',
    'South Khorasan',
    'Kerman',
    'North Khorasan',
    'Zanjan',
    'Char Mahal o Bakhtiari',
    'Bushehr',
  ],
  'Korea, Republic of': [
    'Seoul',
    'Busan',
    'Daegu',
    'Incheon',
    'Gwangju',
    'Daejeon',
    'Ulsan',
    'Sejong',
    'Gyeonggi',
    'Gangwon',
    'Chungbuk',
    'N Jeolla',
    'S Jeolla',
    'Gyeongbuk',
    'Jeju',
  ],
  Spain: [
    'Andalusia',
    'Catalonia',
    'Community of Madrid',
    'Valencian Community',
    'Galicia',
    'Castile and Leon',
    'Basque',
    'Castilla-La Mancha',
    'Canary Islands',
    'Region of Murcia',
    'Aragón',
    'Extremadura',
    'Balearic Islands',
    'Asturias',
    'Navarre',
    'Cantabria',
    'La Rioja',
    'Ceuta',
    'Melilla',
  ],
  Germany: [
    'Baden-Wurttemberg',
    'Bavaria',
    'Berlin',
    'Brandenburg',
    'Bremen',
    'Hamburg',
    'Hesse',
    'Lower Saxony',
    'Mecklenburg-Vorpommern',
    'North Rhine-Westphalia',
    'Rhineland-Palatinate',
    'Saarland',
    'Saxony',
    'Saxony-Anhalt',
    'Schleswig-Holstein',
    'Thuringia',
  ],
  Switzerland: [
    'Aargau',
    'Appenzell Ausserrhoden',
    'Basel-Landschaft',
    'Basel-Stadt',
    'Bern',
    'Fribourg',
    'Geneva',
    'Glarus',
    'Graubunden; Grisons',
    'Jura',
    'Luzern',
    'Neuchatel',
    'Nidwalden',
    'Obwalden',
    'Schaffhausen',
    'Schwyz',
    'Solthurn',
    'St Gallen',
    'Thurgau',
    'Ticino',
    'Uri',
    'Valais',
    'Vaud',
    'Zug',
    'Zurich',
  ],
  Iraq: [
    'Al Anbar',
    'Babil',
    'Baghdad',
    'Basra',
    'Dhi Qar',
    'Al-Qādisiyyah',
    'Diyala',
    'Dohuk',
    'Erbil (Erbîl)',
    'Halabja (Helebce)',
    'Karbala',
    'Kirkuk',
    'Maysan',
    'Muthanna',
    'Najaf',
    'Nineveh',
    'Saladin',
    'Sulaymaniyah (Slêmanî)',
    'Wasit',
    'Kurdistan',
  ],
};
