export const Regions = {
  USA: [
    'New York       ',
    'Washington',
    'California',
    'New Jersey',
    'Michigan',
    'Illinois',
    'Florida',
    'Louisiana',
    'Texas',
    'Massachusetts',
    'Georgia',
    'Pennsylvania',
    'Colorado',
    'Tennessee',
    'Wisconsin',
    'North Carolina',
    'Ohio',
    'Connecticut',
    'Maryland',
    'South Carolina',
    'Nevada',
    'Virginia',
    'Mississippi',
    'Minnesota',
    'Utah',
    'Alabama',
    'Indiana',
    'Arkansas',
    'Arizona',
    'Oregon',
    'Kentucky',
    'District of Columbia',
    'Missouri',
    'Maine',
    'Iowa',
    'Rhode Island',
    'Kansas',
    'New Hampshire',
    'Oklahoma',
    'Diamond Princess',
    'Delaware',
    'New Mexico',
    'Nebraska',
    'Hawaii',
    'Idaho',
    'Vermont',
    'North Dakota',
    'Grand Princess',
    'Wyoming',
    'Montana',
    'Puerto Rico',
    'Alaska',
    'Guam',
    'South Dakota',
    'West Virginia',
    'United States Virgin Islands    ',
  ],
  China: [
    'Hubei',
    'Guangdong',
    'Beijing',
    'Shanghai',
    'Zhejiang',
    'Tianjin',
    'Chongqing',
    'Jiangxi',
    'Shandong',
    'Henan',
    'Hunan',
    'Sichuan',
    'Yunnan',
    'Fujian',
    'Liaoning',
    'Hainan',
    'Anhui',
    'Guizhou',
    'Guangxi',
    'Hebei',
    'Jilin',
    'Heilongjiang',
    'Shaanxi',
    'Xinjiang',
    'Gansu',
    'Inner Mongolia',
  ],
  Italy: [
    'Lombardia',
    'Veneto',
    'Emilia - Romagna',
    'Piemonte',
    'Trentino',
    'Sicilia',
    'Toscana',
    'Liguria',
    'Marche',
    'Puglia',
    'Lazio',
    'Abruzzo',
    'Calabria',
    'Campania',
    'Umbria',
    'Friuli',
    'Bolzano',
    'Sardegna',
    'Basilicata',
    "Valle d'Aosta",
  ],
};
